spring:
  application:
    name: cards
  profiles:
    active: qa
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
   init:
     mode: always
  config:
    import: optional:configserver:http://localhost:8071
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

springdoc:
  api-docs:
    version: openapi_3_0
server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: "*"